### ISSUE TITLE
wants to add some regex cheats

### ISSUE THREAD

**Issue by sifa123** [chryz-hub/top-languages-cheat#18]
Hi @chryzcodez , I would like to add some regex cheats as you have added anchors. There are many types of cheats like quantifiers (*, ?,...), special characters (\r, \zzz,...), etc. If you want, I will make a pr then

**Comment by chryzcodez** [comment]
You are very welcome @sifa123. Please do, contribute to the repositories.

**Comment by sifa123** [comment]
Great!!! Thanks @chryzcodez
